name: CI with Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache a dummy directory to demonstrate caching
      - name: Cache dummy folder
        id: cache
        uses: actions/cache@v4
        with:
          path: dummy-cache
          key: cache-d2bb490

      - name: prime-cache-d2bb490
        run: |
          if [ "${{ steps.cache.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss."
            # Create the dummy folder to populate the cache next run
            mkdir -p dummy-cache
            echo "This is cached content" > dummy-cache/file.txt
          fi

      - name: Dummy step
        run: echo "Workflow ran successfully!"
