name: Cache Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache npm dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-d2bb490

      - name: Install dependencies
        run: npm install

      - name: Print cache hit/miss
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"

